# Generated by Django 4.2.3 on 2023-08-24 02:54

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("id_asal", models.IntegerField()),
                ("email", models.CharField(max_length=500, null=True)),
                ("first_name", models.CharField(max_length=500)),
                ("last_name", models.CharField(max_length=500)),
                ("avatar", models.CharField(max_length=500)),
                ("deleted_at", models.DateTimeField()),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
