# Generated by Django 4.2.3 on 2023-08-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("akasia", "0002_alter_user_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id_asal",
            field=models.IntegerField(null=True),
        ),
    ]
