# Generated by Django 4.2.3 on 2023-08-03 09:56

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Penerbit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_penerbit", models.CharField(default="", max_length=100)),
                ("nama", models.CharField(default="", max_length=100)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("telpn", models.CharField(blank=True, max_length=100, null=True)),
                ("asal", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Penerbit",
                "verbose_name_plural": "Penerbit",
            },
        ),
        migrations.CreateModel(
            name="Buku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("isbn", models.CharField(default="", max_length=100)),
                ("judul", models.CharField(default="", max_length=100)),
                ("tahun_terbit", models.IntegerField(default=1991)),
                (
                    "pengarang",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("url_image", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "penerbit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.penerbit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buku",
                "verbose_name_plural": "Buku",
            },
        ),
    ]
