# Generated by Django 4.2.3 on 2023-08-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="buku",
            name="kategori",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="buku",
            name="sub_kategori",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
