# Generated by Django 4.2.3 on 2023-08-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_buku_kategori_buku_sub_kategori"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="jumlah_stock",
            field=models.IntegerField(),
        ),
    ]
